"""Turns a fragment shader's int output at Location 7 into the stencil export
built-in, for the FH1 depth-and-stencil transfers: glslang's HLSL front end
has no SV_StencilRef. Reads a SPIR-V module, writes it as a C header in
glslang's --vn format.

Usage: spirv_stencil_export.py input.spv output.h variable_name
"""
import struct
import sys

OP_CAPABILITY, OP_EXTENSION, OP_DECORATE = 17, 10, 71
DECORATION_BUILTIN, DECORATION_LOCATION = 11, 30
BUILTIN_FRAG_STENCIL_REF_EXT = 5014
CAPABILITY_STENCIL_EXPORT_EXT = 5013
STENCIL_LOCATION = 7


def string_words(text):
    data = text.encode('ascii') + b'\0'
    data += b'\0' * (-len(data) % 4)
    return list(struct.unpack(f'<{len(data) // 4}I', data))


def main():
    source, header, name = sys.argv[1:4]
    data = open(source, 'rb').read()
    words = list(struct.unpack(f'<{len(data) // 4}I', data))
    out = words[:5]
    position = 5
    patched = False
    added_header = False
    while position < len(words):
        count, opcode = words[position] >> 16, words[position] & 0xFFFF
        instruction = words[position:position + count]
        if opcode == OP_DECORATE and instruction[2] == DECORATION_LOCATION and \
                instruction[3] == STENCIL_LOCATION:
            instruction = [instruction[0], instruction[1], DECORATION_BUILTIN,
                           BUILTIN_FRAG_STENCIL_REF_EXT]
            patched = True
        out += instruction
        position += count
        # After the last OpCapability: the capability and the extension.
        if (not added_header and opcode == OP_CAPABILITY and
                (words[position] & 0xFFFF) != OP_CAPABILITY):
            out += [(2 << 16) | OP_CAPABILITY, CAPABILITY_STENCIL_EXPORT_EXT]
            extension = string_words('SPV_EXT_shader_stencil_export')
            out += [((1 + len(extension)) << 16) | OP_EXTENSION] + extension
            added_header = True
    if not patched or not added_header:
        sys.exit(f'{source}: no output at Location {STENCIL_LOCATION} to patch')
    lines = [f'const uint32_t {name}[] = {{']
    for i in range(0, len(out), 8):
        lines.append('\t' + ','.join(f'0x{w:08x}' for w in out[i:i + 8]) + ',')
    lines[-1] = lines[-1].rstrip(',')
    lines.append('};')
    with open(header, 'w', newline='\n') as f:
        f.write('\t// Generated by spirv_stencil_export.py\n\t #pragma once\n' + '\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
