/**
 ******************************************************************************
 * Xenia : Xbox 360 Emulator Research Project                                 *
 ******************************************************************************
 * Copyright 2022 Ben Vanik. All rights reserved.                             *
 * Released under the BSD license - see LICENSE in the root for more details. *
 ******************************************************************************
 *
 * @modified    Tom Clay, 2026 - Adapted for ReXGlue runtime
 */

#pragma once

#include <array>
#include <atomic>
#include <cstring>
#include <functional>
#include <deque>
#include <condition_variable>
#include <memory>
#include <mutex>
#include <queue>
#include <string>
#include <unordered_map>
#include <vector>

#include <rex/graphics/register_file.h>
#include <rex/graphics/registers.h>
#include <rex/graphics/xenos.h>
#include <rex/memory.h>
#include <rex/memory/ring_buffer.h>
#include <rex/system/xthread.h>
#include <rex/thread.h>
#include <rex/ui/presenter.h>

namespace rex::stream {
class ByteStream;
}  // namespace rex::stream

namespace rex::graphics {

class GraphicsSystem;
class Shader;

enum class ReadbackResolveMode {
  kDisabled,
  kFast,
  kSome,
  kFull,
};

struct SwapState {
  // Lock must be held when changing data in this structure.
  std::mutex mutex;
  // Dimensions of the framebuffer textures. Should match window size.
  uint32_t width = 0;
  uint32_t height = 0;
  // Current front buffer, being drawn to the screen.
  uintptr_t front_buffer_texture = 0;
  // Current back buffer, being updated by the CP.
  uintptr_t back_buffer_texture = 0;
  // Backend data
  void* backend_data = nullptr;
  // Whether the back buffer is dirty and a swap is pending.
  bool pending = false;
};

enum class SwapMode {
  kNormal,
  kIgnored,
};

enum class GammaRampType {
  kUnknown = 0,
  kTable,
  kPWL,
};

class CommandProcessor {
 public:
  enum class SwapPostEffect {
    kNone,
    kFxaa,
    kFxaaExtreme,
  };

  CommandProcessor(GraphicsSystem* graphics_system, system::KernelState* kernel_state);
  virtual ~CommandProcessor();

  uint32_t counter() const { return counter_; }
  void increment_counter() { counter_++; }

  Shader* active_vertex_shader() const { return active_vertex_shader_; }
  Shader* active_pixel_shader() const { return active_pixel_shader_; }
  // The draw resolution scale in use (any thread): the backend sets it at
  // setup and when it switches scale at run time.
  uint32_t draw_resolution_scale() const {
    return draw_resolution_scale_.load(std::memory_order_relaxed);
  }
  uint64_t bin_mask() const { return bin_mask_; }
  uint64_t bin_select() const { return bin_select_; }

  virtual bool Initialize();
  virtual void Shutdown();

  void CallInThread(std::function<void()> fn);

  virtual void ClearCaches();
  virtual void InvalidateGpuMemory();

  // "Desired" is for the external thread managing the post-processing effect.
  SwapPostEffect GetDesiredSwapPostEffect() const { return swap_post_effect_desired_; }
  void SetDesiredSwapPostEffect(SwapPostEffect swap_post_effect);
  // Implementations must not make assumptions that the front buffer will
  // necessarily be a resolve destination - it may be a texture generated by any
  // means like written to by the CPU or loaded from a file (the disclaimer
  // screen right in the beginning of 4D530AA4 is not a resolved render target,
  // for instance).
  virtual void IssueSwap(uint32_t frontbuffer_ptr, uint32_t frontbuffer_width,
                         uint32_t frontbuffer_height) = 0;

  // May be called not only from the command processor thread when the command
  // processor is paused, and the termination of this function may be explicitly
  // awaited.
  virtual void InitializeShaderStorage(const std::filesystem::path& cache_root, uint32_t title_id,
                                       bool blocking);

  void InitializeRingBuffer(uint32_t ptr, uint32_t size_log2);
  void EnableReadPointerWriteBack(uint32_t ptr, uint32_t block_size_log2);

  void UpdateWritePointer(uint32_t value);

  void ExecutePacket(uint32_t ptr, uint32_t count);

  // Frame dumps: while set, the recorder sees the raw (big-endian) dwords of
  // every packet executed, indirect buffers flattened into their packets.
  using PacketRecorder = std::function<void(const uint32_t* dwords, uint32_t count)>;
  void SetPacketRecorder(PacketRecorder recorder) { packet_recorder_ = std::move(recorder); }
  // Executes big-endian packets from host memory as if read from the ring.
  bool ExecuteHostPackets(const uint32_t* dwords, uint32_t count);
  // Replays a frame dump requested at startup (fh1_frame_replay); called on
  // the command processor thread once shader storage is initialized.
  virtual void RunRequestedFrameReplay() {}

  bool is_paused() const { return paused_; }
  void Pause();
  void Resume();
  // While paused, wakes the commands thread once to release the caches it
  // can rebuild (OnReduceMemory), then pauses it again.
  void ReduceMemoryWhilePaused();

  bool Save(::rex::stream::ByteStream* stream);
  bool Restore(::rex::stream::ByteStream* stream);

 protected:
  struct IndexBufferInfo {
    xenos::IndexFormat format = xenos::IndexFormat::kInt16;
    xenos::Endian endianness = xenos::Endian::kNone;
    uint32_t count = 0;
    uint32_t guest_base = 0;
    size_t length = 0;
  };

  void WorkerThreadMain();
  virtual bool SetupContext() = 0;
  virtual void ShutdownContext() = 0;

  virtual void WriteRegister(uint32_t index, uint32_t value);
  uint32_t ReadRegisterValue(uint32_t index) const;
  virtual void WriteRegistersFromMem(uint32_t start_index, uint32_t* base, uint32_t num_registers);
  // As WriteRegistersFromMem with host byte order values: the recorder's runs,
  // which the decoder swapped when recording them. The default swaps them back
  // for backends that only override WriteRegistersFromMem.
  virtual void WriteRegistersHost(uint32_t start_index, const uint32_t* values,
                                  uint32_t num_registers);
  // gpu_template_stats (DR-4.2's first stage, recorder thread): each draw's
  // signature (register state, shaders, the fetch constants it uses, the draw
  // packet) in the indirect buffer execution it belongs to, compared at the
  // buffer's end with the same buffer's previous execution, to size what a
  // compiled replay of repeated buffers could skip.
  void TemplateStatsIbBegin(uint64_t ib_key, bool repeat);
  void TemplateStatsIbEnd();
  static constexpr size_t kTemplateParts = 5;
  void TemplateStatsDraw(const uint64_t (&parts)[kTemplateParts]);
  void TemplateStatsFrame();
  struct TemplateStatsIb {
    uint64_t key = 0;
    bool repeat = false;
    std::vector<std::array<uint64_t, kTemplateParts>> signatures;
  };
  std::vector<TemplateStatsIb> template_stats_stack_;
  std::unordered_map<uint64_t, std::vector<std::array<uint64_t, kTemplateParts>>>
      template_stats_last_;
  std::unordered_map<uint64_t, uint32_t> template_stats_occurrences_;
  struct TemplateStatsCounts {
    uint64_t frames = 0, draws = 0, draws_in_ibs = 0, draws_in_repeated_ibs = 0,
             draws_matching = 0, draws_in_matching_runs = 0, draws_in_matching_ibs = 0,
             ibs = 0, matching_ibs = 0;
    // Draws at a matching position whose part n matches.
    uint64_t parts_matching[kTemplateParts] = {};
  } template_stats_;
  // A sample of buffers: the register file at their first draw, to count
  // which registers differ from the previous execution's.
  std::unordered_map<uint64_t, std::vector<uint32_t>> template_stats_registers_;
  std::unordered_map<uint32_t, uint64_t> template_stats_register_diffs_;
  // CommandProcessor::WriteRegistersFromMem's own work for host order values.
  void WriteRegistersHostBase(uint32_t start_index, const uint32_t* values,
                              uint32_t num_registers);
  std::vector<uint32_t> write_registers_host_scratch_;
  virtual void WriteRegisterRangeFromRing(memory::RingBuffer* ring, uint32_t base,
                                          uint32_t num_registers);
  void WriteALURangeFromRing(memory::RingBuffer* ring, uint32_t base, uint32_t num_registers);
  void WriteFetchRangeFromRing(memory::RingBuffer* ring, uint32_t base, uint32_t num_registers);
  void WriteBoolRangeFromRing(memory::RingBuffer* ring, uint32_t base, uint32_t num_registers);
  void WriteLoopRangeFromRing(memory::RingBuffer* ring, uint32_t base, uint32_t num_registers);
  void WriteREGISTERSRangeFromRing(memory::RingBuffer* ring, uint32_t base, uint32_t num_registers);
  void WriteALURangeFromMem(uint32_t start_index, uint32_t* base, uint32_t num_registers);
  void WriteFetchRangeFromMem(uint32_t start_index, uint32_t* base, uint32_t num_registers);
  void WriteBoolRangeFromMem(uint32_t start_index, uint32_t* base, uint32_t num_registers);
  void WriteLoopRangeFromMem(uint32_t start_index, uint32_t* base, uint32_t num_registers);
  void WriteREGISTERSRangeFromMem(uint32_t start_index, uint32_t* base, uint32_t num_registers);

  PacketRecorder packet_recorder_;

  const reg::DC_LUT_30_COLOR* gamma_ramp_256_entry_table() const {
    return gamma_ramp_256_entry_table_;
  }
  const reg::DC_LUT_PWL_DATA* gamma_ramp_pwl_rgb() const { return gamma_ramp_pwl_rgb_[0]; }
  virtual void OnGammaRamp256EntryTableValueWritten() {}
  virtual void OnGammaRampPWLValueWritten() {}

  virtual void MakeCoherent();
  virtual void PrepareForWait();
  virtual void ReturnFromWait();

  uint32_t ExecutePrimaryBuffer(uint32_t start_index, uint32_t end_index);
  virtual void OnPrimaryBufferEnd() {}
  // Before the command processor does something the guest CPU can observe
  // (writes guest memory, raises an interrupt, swaps, advances the ring read
  // pointer): results the CPU may read from then on must be in guest memory.
  virtual void FlushCpuVisibleResults() {}
  virtual void ExecuteIndirectBuffer(uint32_t ptr, uint32_t length);
  bool ExecutePacket(memory::RingBuffer* reader);
  bool ExecutePacketType0(memory::RingBuffer* reader, uint32_t packet);
  bool ExecutePacketType1(memory::RingBuffer* reader, uint32_t packet);
  bool ExecutePacketType2(memory::RingBuffer* reader, uint32_t packet);
  bool ExecutePacketType3(memory::RingBuffer* reader, uint32_t packet);
  bool ExecutePacketType3_ME_INIT(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_NOP(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_INTERRUPT(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_XE_SWAP(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_INDIRECT_BUFFER(memory::RingBuffer* reader, uint32_t packet,
                                          uint32_t count);
  bool ExecutePacketType3_WAIT_REG_MEM(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_REG_RMW(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_REG_TO_MEM(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_MEM_WRITE(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_COND_WRITE(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_EVENT_WRITE(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_EVENT_WRITE_SHD(memory::RingBuffer* reader, uint32_t packet,
                                          uint32_t count);
  bool ExecutePacketType3_EVENT_WRITE_EXT(memory::RingBuffer* reader, uint32_t packet,
                                          uint32_t count);
  virtual bool ExecutePacketType3_EVENT_WRITE_ZPD(memory::RingBuffer* reader, uint32_t packet,
                                                  uint32_t count);
  bool ExecutePacketType3Draw(memory::RingBuffer* reader, uint32_t packet, const char* opcode_name,
                              uint32_t viz_query_condition, uint32_t count_remaining);
  bool ExecutePacketType3_DRAW_INDX(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_DRAW_INDX_2(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_SET_CONSTANT(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_SET_CONSTANT2(memory::RingBuffer* reader, uint32_t packet,
                                        uint32_t count);
  bool ExecutePacketType3_LOAD_ALU_CONSTANT(memory::RingBuffer* reader, uint32_t packet,
                                            uint32_t count);
  bool ExecutePacketType3_SET_SHADER_CONSTANTS(memory::RingBuffer* reader, uint32_t packet,
                                               uint32_t count);
  bool ExecutePacketType3_IM_LOAD(memory::RingBuffer* reader, uint32_t packet, uint32_t count);
  bool ExecutePacketType3_IM_LOAD_IMMEDIATE(memory::RingBuffer* reader,

                                            uint32_t packet, uint32_t count);
  bool ExecutePacketType3_INVALIDATE_STATE(memory::RingBuffer* reader, uint32_t packet,
                                           uint32_t count);
  bool ExecutePacketType3_VIZ_QUERY(memory::RingBuffer* reader, uint32_t packet, uint32_t count);

  virtual Shader* LoadShader(xenos::ShaderType shader_type, uint32_t guest_address,
                             const uint32_t* host_address, uint32_t dword_count) = 0;
  // With the microcode hash computed by the caller (the decoder while split);
  // backends that hash the same way take it, others hash again.
  virtual uint64_t HashShaderMicrocode(const uint32_t* host_address, uint32_t dword_count) const {
    (void)host_address;
    (void)dword_count;
    return 0;
  }
  virtual Shader* LoadShaderHashed(xenos::ShaderType shader_type, uint32_t guest_address,
                                   const uint32_t* host_address, uint32_t dword_count,
                                   uint64_t hash) {
    (void)hash;
    return LoadShader(shader_type, guest_address, host_address, dword_count);
  }

  virtual bool IssueDraw(xenos::PrimitiveType prim_type, uint32_t index_count,
                         IndexBufferInfo* index_buffer_info, bool major_mode_explicit) = 0;
  virtual bool IssueCopy() = 0;

  // Decode/record split (gpu_record_thread, PB-2.11): this thread keeps
  // decoding PM4 against a shadow register file while a recorder thread
  // applies the register writes and runs the backend work (draws, copies,
  // shader loads, swaps) in the same order. Packets whose effects the CPU
  // sees wait for the recorder first. Backends opt in.
  virtual bool SupportsRecordThread() const { return false; }
  bool record_split() const { return record_split_; }
  // The register file the decoder reads: the shadow while split.
  RegisterFile& decode_regs() { return record_split_ ? *decode_register_file_ : *register_file_; }
  // Register writes from packets: applied directly, or recorded while split.
  void PacketWriteRegister(uint32_t index, uint32_t value);
  // `base` is guest (big-endian) data; recorded by copy while split.
  void PacketWriteRegistersFromMem(uint32_t start_index, const uint32_t* base,
                                   uint32_t num_registers);
  // Runs `fn` on the recorder in order (directly when not split).
  void RecordCall(std::function<void()> fn);
  // Hands the recorded work so far to the recorder.
  void PublishRecordBatch();
  // Bumped whenever a register other than the shader constants and the
  // per-draw ones (index buffer, draw initiator, event initiator, scratch,
  // coherency, constant flushes) changes value: derivations from register
  // state can be reused while it holds.
  uint64_t state_epoch_ = 1;
  // The same register set's content as a Zobrist-style hash, updated per
  // changed register: equal hashes mean equal state, so derivations can be
  // reused across draws and frames, not only while nothing changes.
  uint64_t state_hash_ = 0;
  static uint64_t StateHashTerm(uint32_t index, uint32_t value) {
    uint64_t x = (uint64_t(index) << 32 | value) * UINT64_C(0x9E3779B97F4A7C15);
    x ^= x >> 29;
    x *= UINT64_C(0xBF58476D1CE4E5B9);
    return x ^ (x >> 32);
  }
  // Registers left out of the state epoch and hash: per-draw ones, and ones
  // no draw derivation reads that change on their own every frame - the
  // command processor's (CP_RB_WPTR moves with every kick), the display
  // controller's (D1GRPH_PRIMARY_SURFACE_ADDRESS alternates with the front
  // buffer) and the host coherency range. With them in, the hash of the same
  // draw differed between frames 98 % of the time (gpu_template_stats), so
  // the hash-keyed memos missed across frames.
  static bool IsPerDrawRegister(uint32_t index) {
    return (index >= XE_GPU_REG_SCRATCH_REG0 && index <= XE_GPU_REG_SCRATCH_REG7) ||
           (index >= XE_GPU_REG_VGT_EVENT_INITIATOR && index <= XE_GPU_REG_VGT_DRAW_INITIATOR) ||
           (index >= XE_GPU_REG_COHER_SIZE_HOST && index <= XE_GPU_REG_COHER_STATUS_HOST) ||
           (index >= 0x01C0 && index <= 0x01FF) || (index >= 0x1800 && index <= 0x19FF) ||
           index >= 0x5000;
  }
  // Returns once the recorder has run everything recorded so far; the
  // recorder is then idle until the next publish, so this thread may touch
  // backend state until it records again.
  void RecordSync();

  // "Actual" is for the command processor thread, to be read by the
  // implementations.
  SwapPostEffect GetActualSwapPostEffect() const { return swap_post_effect_actual_; }

  // Shared readback resolve mode with backend legacy-flag alias support.
  ReadbackResolveMode GetReadbackResolveMode(bool legacy_readback_resolve_enabled) const;
#if REX_HAS_VULKAN
  // Shared memexport readback enable state with backend legacy-flag override support.
  bool IsReadbackMemexportEnabled(bool legacy_backend_flag) const;
#endif  // REX_HAS_VULKAN

  memory::Memory* memory_ = nullptr;
  system::KernelState* kernel_state_ = nullptr;
  GraphicsSystem* graphics_system_ = nullptr;
  RegisterFile* register_file_ = nullptr;

  std::atomic<bool> worker_running_;
  system::object_ref<system::XHostThread> worker_thread_;

  struct PendingCall {
    std::function<void()> fn;
    // Runs on the decoding thread even when a recorder thread is split off.
    bool on_worker = false;
  };
  void CallInWorkerThread(std::function<void()> fn);
  // On the worker thread, between guest commands: parks it until Resume,
  // doing any memory reduction requested meanwhile.
  void WorkerWaitWhilePaused();
  // Called on the thread that records host GPU work, with the GPU idle.
  virtual void OnReduceMemory() {}

  // Pushed from other threads (the UI's lifecycle events), popped by the
  // worker.
  std::mutex pending_mutex_;
  std::queue<PendingCall> pending_fns_;
  std::atomic<bool> pending_any_{false};

  std::mutex pause_mutex_;
  std::condition_variable pause_signal_;
  bool worker_paused_ = false;            // Protected by pause_mutex_.
  bool reduce_memory_requested_ = false;  // Protected by pause_mutex_.

  // MicroEngine binary from PM4_ME_INIT
  std::vector<uint32_t> me_bin_;

  uint32_t counter_ = 0;

  uint32_t primary_buffer_ptr_ = 0;
  uint32_t primary_buffer_size_ = 0;

  uint32_t read_ptr_index_ = 0;
  uint32_t read_ptr_update_freq_ = 0;
  uint32_t read_ptr_writeback_ptr_ = 0;

  std::unique_ptr<rex::thread::Event> write_ptr_index_event_;
  std::atomic<uint32_t> write_ptr_index_;

  // Some titles submit writes beyond the emulated register file range in PM4
  // packets. Preserve these values so dependent packet logic can still observe
  // them instead of dropping the write entirely.
  std::unordered_map<uint32_t, uint32_t> extended_register_values_;

  uint64_t bin_select_ = 0xFFFFFFFFull;
  uint64_t bin_mask_ = 0xFFFFFFFFull;

  Shader* active_vertex_shader_ = nullptr;
  Shader* active_pixel_shader_ = nullptr;
  std::atomic<uint32_t> draw_resolution_scale_{1};
  // The next draw's index in its frame (fh1_debug_skip_draws, fh1_debug_log_draws).
  uint32_t debug_frame_draw_index_ = 0;
  uint64_t observation_frame_sequence_ = 1;
  bool paused_ = false;

  // By default (such as for tools), post-processing is disabled.
  // "Desired" is for the external thread managing the post-processing effect.
  SwapPostEffect swap_post_effect_desired_ = SwapPostEffect::kNone;
  SwapPostEffect swap_post_effect_actual_ = SwapPostEffect::kNone;

#if REX_HAS_VULKAN
  // Set by backend command processors to their legacy memexport readback cvar
  // name (for explicit-override compatibility).
  const char* legacy_readback_memexport_cvar_name_ = nullptr;
#endif  // REX_HAS_VULKAN

 private:
  struct RecordBatch {
    // Records: kRecordRun start count dwords (host order)..., kRecordOne index value,
    // kRecordCall function-index.
    std::vector<uint32_t> words;
    std::vector<std::function<void()>> fns;
  };
  static constexpr uint32_t kRecordRun = 0;
  static constexpr uint32_t kRecordOne = 1;
  static constexpr uint32_t kRecordCall = 2;
  struct DrawRecord {
    uint32_t packet;
    uint32_t initiator;
    uint32_t is_indexed;
    uint32_t padding;
    IndexBufferInfo index_buffer_info;
    const char* opcode_name;
  };
  static constexpr uint32_t kRecordDraw = 3;
  static constexpr size_t kDrawRecordWords = (sizeof(DrawRecord) + 3) / 4;
  // The draw half of a draw packet (registers already written): the backend
  // draw and its failure reporting.
  void ExecuteDrawRecord(const DrawRecord& record);
  uint32_t record_batch_draws_ = 0;
  void StartRecordThread();
  void StopRecordThread();
  void RecordThreadMain();
  void ExecuteRecordBatch(RecordBatch& batch);
  bool record_split_ = false;
  // gpu_record_elide_unchanged_registers, read when the split starts.
  bool elide_unchanged_registers_ = false;
  // Appends a register run (big-endian source words) to the record batch.
  void RecordRegisterRun(uint32_t start_index, const uint32_t* base, uint32_t num_registers);
  std::unique_ptr<RegisterFile> decode_register_file_;
  std::unordered_map<uint32_t, uint32_t> decode_extended_register_values_;
  std::unique_ptr<RecordBatch> record_batch_;
  // The last float constant run recorded, while it is still the batch's last
  // record: a following run a short gap after it extends it instead.
  const RecordBatch* last_constant_run_batch_ = nullptr;
  size_t last_constant_run_offset_ = 0;
  size_t last_constant_run_end_ = 0;
  std::mutex record_mutex_;
  std::condition_variable record_ready_;
  std::condition_variable record_done_;
  std::deque<std::unique_ptr<RecordBatch>> record_queue_;
  std::vector<std::unique_ptr<RecordBatch>> record_free_;
  uint64_t record_published_ = 0;
  uint64_t record_completed_ = 0;
  bool record_stop_ = false;
  system::object_ref<system::XHostThread> record_thread_;

  reg::DC_LUT_30_COLOR gamma_ramp_256_entry_table_[256] = {};
  reg::DC_LUT_PWL_DATA gamma_ramp_pwl_rgb_[128][3] = {};
  uint32_t gamma_ramp_rw_component_ = 0;
};

}  // namespace rex::graphics
